### ISSUE TITLE
Some texts are very hard to read in dark mode

### ISSUE THREAD

**Issue by mohsenkhosroanjam** [BDadmehr0/DailyTasker#18]
When you put the app on dark mode, "add task" button, status combo box, and search field are hard to read. Please see the attachment.
Steps to reproduce:
1- change the theme to dark mode
Window, version: 11 Enterprise
![image](https://github.com/user-attachments/assets/e147951d-69a6-4640-942a-b400463ffab1)

**Comment by BDadmehr0** [comment]
Unfortunately, I don't have a Windows operating system to test this easily. I will provide updates in the program and let you know. Thank you for reporting the issue.
@mohsenkhosroanjam

**Comment by BDadmehr0** [comment]
I have worked on this issue, but I'm not sure if it has also been resolved on Windows.

![Uploading Screenshot_2024-12-20_13-48-44.png…]()

**Comment by mohsenkhosroanjam** [comment]
@BDadmehr0 Thanks for your time. I just checked it on the main branch and the issue remains.
![image](https://github.com/user-attachments/assets/d8f3efb2-104c-42cc-ac87-73a89a49af63)

**Comment by BDadmehr0** [comment]
try again! @mohsenkhosroanjam

**Comment by mohsenkhosroanjam** [comment]
@BDadmehr0 Thanks. Although this issue has been fixed, a new bug has been created. Should I create a new issue for it?
Please see the attachment and see "add task", "search tasks", and "combo box".
https://github.com/user-attachments/assets/08db9571-b868-4185-99db-f2186dbc12c6

**Comment by BDadmehr0** [comment]
> @BDadmehr0 Thanks. Although this issue has been fixed, a new bug has been created. Should I create a new issue for it?
> Please see the attachment and see "add task", "search tasks", and "combo box".
> https://github.com/user-attachments/assets/08db9571-b868-4185-99db-f2186dbc12c6
> 
> 

If these issues occurred when I merged this patch, there is no need, and I don't think a new issue needs to be created here. I noticed the problem and will inform you right here.
