### ISSUE TITLE
Change the color of pending tasks

### ISSUE THREAD

**Issue by mohsenkhosroanjam** [BDadmehr0/DailyTasker#20]
The color of pending tasks is not suitable. It is better to choose a color that improves their readability. Please, see the attachment. 
![image](https://github.com/user-attachments/assets/4b7ac7c6-9149-4634-bfdb-fafa9b67a8c0)

**Comment by BDadmehr0** [comment]
What color do you suggest? @mohsenkhosroanjam

**Comment by mohsenkhosroanjam** [comment]
@BDadmehr0 Can we change the color based on the theme?
I was thinking about black color but it is not suitable in dark mode!

**Comment by BDadmehr0** [comment]
> @BDadmehr0 Can we change the color based on the theme?
> I was thinking about black color but it is not suitable in dark mode!

Sure, if you make the changes and create a PR for me, I would appreciate it. Thank you

**Comment by mohsenkhosroanjam** [comment]
@BDadmehr0 Sure. I am not a software developer but I would love to try to get it fixed. I will send you a PR soon.

**Comment by BDadmehr0** [comment]
I would be happy if you work on this issue. It's simple; you just need to know where the object is and with what argument it changes color.
@mohsenkhosroanjam

**Comment by mohsenkhosroanjam** [comment]
@BDadmehr0 Sure, dude. I have been working on it and I just found the right place. I have changed the color of tasks to black only in light mode because I feel the readability is suitable in dark mode. Looking forward to hearing your feedback. I am going to send you a PR.

**Comment by BDadmehr0** [comment]
> @BDadmehr0 Sure, dude. I have been working on it and I just found the right place. I have changed the color of tasks to black only in light mode because I feel the readability is suitable in dark mode. Looking forward to hearing your feedback. I am going to send you a PR.

Make any changes needed; I will review them. Thank you.
