### ISSUE TITLE
Changing the theme from dark to light has an issue

### ISSUE THREAD

**Issue by mohsenkhosroanjam** [BDadmehr0/DailyTasker#22]
Steps to reproduce:
1- change the theme from light to dark
2- then, change the therefrom dark to light again
The background color of the tasks is changed. Please see the attachment to understand the issue better. 
Windows, Version: 11 Enterprise

https://github.com/user-attachments/assets/457a5f9e-2fb5-457f-9066-5d90867bd5f2

**Comment by BDadmehr0** [comment]
Thank you for the update. The issue has been resolved, and you can use it now. @mohsenkhosroanjam

**Comment by mohsenkhosroanjam** [comment]
@BDadmehr0 Thanks, it is fixed dude
